{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d183d124-d016-439d-8dad-56c40e8699e4",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "CyberPatriot Linux Security Automation Script\n",
    "Helps systematically complete Linux security tasks for CyberPatriot competitions\n",
    "\"\"\"\n",
    "\n",
    "import os\n",
    "import subprocess\n",
    "import sys\n",
    "from datetime import datetime\n",
    "\n",
    "class Colors:\n",
    "    GREEN = '\\033[92m'\n",
    "    YELLOW = '\\033[93m'\n",
    "    RED = '\\033[91m'\n",
    "    BLUE = '\\033[94m'\n",
    "    BOLD = '\\033[1m'\n",
    "    END = '\\033[0m'\n",
    "\n",
    "def print_header(text):\n",
    "    print(f\"\\n{Colors.BOLD}{Colors.BLUE}{'='*60}{Colors.END}\")\n",
    "    print(f\"{Colors.BOLD}{Colors.BLUE}{text.center(60)}{Colors.END}\")\n",
    "    print(f\"{Colors.BOLD}{Colors.BLUE}{'='*60}{Colors.END}\\n\")\n",
    "\n",
    "def print_success(text):\n",
    "    print(f\"{Colors.GREEN}✓ {text}{Colors.END}\")\n",
    "\n",
    "def print_warning(text):\n",
    "    print(f\"{Colors.YELLOW}⚠ {text}{Colors.END}\")\n",
    "\n",
    "def print_error(text):\n",
    "    print(f\"{Colors.RED}✗ {text}{Colors.END}\")\n",
    "\n",
    "def run_command(cmd, description, ask=True):\n",
    "    \"\"\"Run a command with user confirmation\"\"\"\n",
    "    if ask:\n",
    "        print(f\"\\n{Colors.BOLD}Task:{Colors.END} {description}\")\n",
    "        print(f\"{Colors.BOLD}Command:{Colors.END} {cmd}\")\n",
    "        response = input(\"Execute? (y/n/skip): \").lower()\n",
    "        if response == 'skip':\n",
    "            return None\n",
    "        elif response != 'y':\n",
    "            return False\n",
    "    \n",
    "    try:\n",
    "        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)\n",
    "        if result.returncode == 0:\n",
    "            print_success(f\"Completed: {description}\")\n",
    "            if result.stdout:\n",
    "                print(result.stdout)\n",
    "            return True\n",
    "        else:\n",
    "            print_error(f\"Failed: {description}\")\n",
    "            if result.stderr:\n",
    "                print(f\"Error: {result.stderr}\")\n",
    "            return False\n",
    "    except Exception as e:\n",
    "        print_error(f\"Exception running command: {e}\")\n",
    "        return False\n",
    "\n",
    "def check_root():\n",
    "    \"\"\"Check if script is running with sudo/root privileges\"\"\"\n",
    "    if os.geteuid() != 0:\n",
    "        print_error(\"This script must be run with sudo privileges!\")\n",
    "        print(\"Usage: sudo python3 cyberpatriot_linux.py\")\n",
    "        sys.exit(1)\n",
    "\n",
    "def system_info():\n",
    "    \"\"\"Display system information\"\"\"\n",
    "    print_header(\"SYSTEM INFORMATION\")\n",
    "    run_command(\"lsb_release -a\", \"Display distribution info\", ask=False)\n",
    "    run_command(\"whoami\", \"Current user\", ask=False)\n",
    "\n",
    "def system_updates():\n",
    "    \"\"\"Handle system updates\"\"\"\n",
    "    print_header(\"SYSTEM UPDATES\")\n",
    "    run_command(\"apt-get update\", \"Update package lists\")\n",
    "    run_command(\"apt-get upgrade -y\", \"Upgrade installed packages\")\n",
    "    run_command(\"apt-get dist-upgrade -y\", \"Perform distribution upgrade\")\n",
    "    run_command(\"apt-get autoremove -y\", \"Remove unnecessary packages\")\n",
    "\n",
    "def configure_automatic_updates():\n",
    "    \"\"\"Configure automatic security updates\"\"\"\n",
    "    print_header(\"AUTOMATIC UPDATES\")\n",
    "    run_command(\"apt-get install unattended-upgrades -y\", \"Install unattended-upgrades\")\n",
    "    run_command(\"dpkg-reconfigure -plow unattended-upgrades\", \"Configure automatic updates\")\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"Verify Software & Updates settings:\" + Colors.END)\n",
    "    print(\"- Open Software & Updates\")\n",
    "    print(\"- Check first four checkmarks in Ubuntu Software tab\")\n",
    "    print(\"- Set 'When there are security updates: Display immediately'\")\n",
    "    print(\"- Set 'When there are other updates: Display immediately'\")\n",
    "\n",
    "def install_antivirus():\n",
    "    \"\"\"Install and configure ClamAV antivirus\"\"\"\n",
    "    print_header(\"ANTIVIRUS (ClamAV)\")\n",
    "    run_command(\"apt-get install clamav clamav-daemon clamtk -y\", \"Install ClamAV\")\n",
    "    run_command(\"systemctl stop clamav-freshclam\", \"Stop freshclam service temporarily\")\n",
    "    run_command(\"freshclam\", \"Update virus definitions\")\n",
    "    run_command(\"systemctl start clamav-freshclam\", \"Start freshclam service\")\n",
    "    \n",
    "    print_warning(\"\\nFull system scan commands (run in background):\")\n",
    "    print(\"  sudo clamscan -r -i --remove=yes / &\")\n",
    "    print(\"  sudo clamscan -r --remove /home &\")\n",
    "\n",
    "def configure_firewall():\n",
    "    \"\"\"Configure UFW firewall\"\"\"\n",
    "    print_header(\"FIREWALL (UFW)\")\n",
    "    run_command(\"apt-get install ufw gufw -y\", \"Install UFW and GUI\")\n",
    "    run_command(\"ufw default deny incoming\", \"Deny incoming connections by default\")\n",
    "    run_command(\"ufw default allow outgoing\", \"Allow outgoing connections\")\n",
    "    \n",
    "    # Check if SSH is needed\n",
    "    print(\"\\n\" + Colors.BOLD + \"Common services:\" + Colors.END)\n",
    "    if input(\"Allow SSH? (y/n): \").lower() == 'y':\n",
    "        run_command(\"ufw allow ssh\", \"Allow SSH\", ask=False)\n",
    "    \n",
    "    services = input(\"Other services to allow (e.g., http https) or press Enter: \").split()\n",
    "    for service in services:\n",
    "        run_command(f\"ufw allow {service}\", f\"Allow {service}\", ask=False)\n",
    "    \n",
    "    run_command(\"ufw enable\", \"Enable firewall\")\n",
    "    run_command(\"ufw status verbose\", \"Show firewall status\", ask=False)\n",
    "\n",
    "def manage_users():\n",
    "    \"\"\"User and password management\"\"\"\n",
    "    print_header(\"USER MANAGEMENT\")\n",
    "    \n",
    "    # List current users\n",
    "    print(Colors.BOLD + \"Current users with login shells:\" + Colors.END)\n",
    "    run_command(\"cut -d: -f1 /etc/passwd\", \"List all users\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"Admin users (sudo group):\" + Colors.END)\n",
    "    run_command(\"getent group sudo\", \"Show sudo group members\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"User Management Tasks:\" + Colors.END)\n",
    "    print(\"1. Change user passwords\")\n",
    "    print(\"2. Change ALL user passwords (bulk)\")\n",
    "    print(\"3. Delete unauthorized users\")\n",
    "    print(\"4. Add missing users\")\n",
    "    print(\"5. Manage sudo privileges\")\n",
    "    print(\"6. Lock/disable accounts\")\n",
    "    print(\"7. Check for UID 0 users (root equivalents)\")\n",
    "    \n",
    "    while True:\n",
    "        choice = input(\"\\nSelect task (1-7) or 'q' to quit: \")\n",
    "        if choice == 'q':\n",
    "            break\n",
    "        elif choice == '1':\n",
    "            user = input(\"Username to change password: \")\n",
    "            run_command(f\"passwd {user}\", f\"Change password for {user}\")\n",
    "        elif choice == '2':\n",
    "            new_pass = input(\"Enter new password for all users: \")\n",
    "            print_warning(\"This will change passwords for all non-system users (UID >= 1000)\")\n",
    "            if input(\"Continue? (yes/no): \").lower() == 'yes':\n",
    "                cmd = f\"for user in $(awk -F: '$3 >= 1000 {{print $1}}' /etc/passwd); do echo \\\"$user:{new_pass}\\\" | chpasswd; echo \\\"Changed password for $user\\\"; done\"\n",
    "                run_command(cmd, \"Change all user passwords\", ask=False)\n",
    "        elif choice == '3':\n",
    "            user = input(\"Username to delete: \")\n",
    "            run_command(f\"userdel -r {user}\", f\"Delete user {user}\")\n",
    "        elif choice == '4':\n",
    "            user = input(\"Username to add: \")\n",
    "            run_command(f\"useradd -m {user}\", f\"Add user {user}\")\n",
    "            run_command(f\"passwd {user}\", f\"Set password for {user}\")\n",
    "        elif choice == '5':\n",
    "            user = input(\"Username: \")\n",
    "            action = input(\"Add to sudo group (a) or remove (r)? \")\n",
    "            if action == 'a':\n",
    "                run_command(f\"usermod -aG sudo {user}\", f\"Add {user} to sudo\")\n",
    "            elif action == 'r':\n",
    "                run_command(f\"deluser {user} sudo\", f\"Remove {user} from sudo\")\n",
    "        elif choice == '6':\n",
    "            user = input(\"Username to lock: \")\n",
    "            run_command(f\"passwd -l {user}\", f\"Lock user {user}\")\n",
    "        elif choice == '7':\n",
    "            print(\"\\n\" + Colors.BOLD + \"Users with UID 0 (should only be root):\" + Colors.END)\n",
    "            run_command(\"awk -F: '$3 == 0 {print $1}' /etc/passwd\", \"Check UID 0 users\", ask=False)\n",
    "\n",
    "def password_policies():\n",
    "    \"\"\"Configure password policies\"\"\"\n",
    "    print_header(\"PASSWORD POLICIES\")\n",
    "    \n",
    "    run_command(\"apt-get install -y libpam-pwquality libpam-cracklib\", \"Install password quality libraries\")\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"Configuring PAM password quality...\" + Colors.END)\n",
    "    print(\"Edit /etc/pam.d/common-password with these settings:\")\n",
    "    print(\"  password requisite pam_pwquality.so retry=3 minlen=12 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1\")\n",
    "    print(\"  password [success=1 default=ignore] pam_unix.so remember=5\")\n",
    "    \n",
    "    if input(\"\\nApply password quality settings? (y/n): \").lower() == 'y':\n",
    "        # Backup first\n",
    "        run_command(\"cp /etc/pam.d/common-password /etc/pam.d/common-password.bak\", \"Backup common-password\", ask=False)\n",
    "        \n",
    "        # Note: Actual sed commands would go here - manual verification recommended\n",
    "        print_warning(\"Manual verification recommended. Edit /etc/pam.d/common-password\")\n",
    "    \n",
    "    # Configure password aging in login.defs\n",
    "    print(\"\\n\" + Colors.BOLD + \"Configuring password aging in /etc/login.defs...\" + Colors.END)\n",
    "    print(\"  PASS_MAX_DAYS 90\")\n",
    "    print(\"  PASS_MIN_DAYS 10\")\n",
    "    print(\"  PASS_WARN_AGE 7\")\n",
    "    \n",
    "    if input(\"\\nApply password aging settings? (y/n): \").lower() == 'y':\n",
    "        run_command(\"cp /etc/login.defs /etc/login.defs.bak\", \"Backup login.defs\", ask=False)\n",
    "        run_command(\"sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS   90/' /etc/login.defs\", \"Set max days\", ask=False)\n",
    "        run_command(\"sed -i 's/^PASS_MIN_DAYS.*/PASS_MIN_DAYS   10/' /etc/login.defs\", \"Set min days\", ask=False)\n",
    "        run_command(\"sed -i 's/^PASS_WARN_AGE.*/PASS_WARN_AGE   7/' /etc/login.defs\", \"Set warn age\", ask=False)\n",
    "    \n",
    "    # Account lockout policy\n",
    "    print(\"\\n\" + Colors.BOLD + \"Configure account lockout (faillock)...\" + Colors.END)\n",
    "    print(\"Add to /etc/pam.d/common-auth:\")\n",
    "    print(\"  auth required pam_faillock.so preauth silent deny=5 unlock_time=1800\")\n",
    "    print(\"  auth [default=die] pam_faillock.so authfail deny=5 unlock_time=1800\")\n",
    "    \n",
    "    # Disable null passwords\n",
    "    print(\"\\n\" + Colors.BOLD + \"Disable null passwords...\" + Colors.END)\n",
    "    if input(\"Remove 'nullok' from PAM config? (y/n): \").lower() == 'y':\n",
    "        run_command(\"sed -i 's/nullok//g' /etc/pam.d/common-auth\", \"Disable null passwords\", ask=False)\n",
    "\n",
    "def disable_autologin():\n",
    "    \"\"\"Disable automatic login\"\"\"\n",
    "    print_header(\"DISABLE AUTOLOGIN\")\n",
    "    \n",
    "    lightdm_config = \"/etc/lightdm/lightdm.conf\"\n",
    "    if os.path.exists(lightdm_config):\n",
    "        print(Colors.BOLD + \"Disabling autologin in lightdm.conf...\" + Colors.END)\n",
    "        run_command(f\"sed -i 's/^autologin-user=/#autologin-user=/' {lightdm_config}\", \"Disable autologin user\", ask=False)\n",
    "        run_command(f\"sed -i 's/^autologin-guest=.*/autologin-guest=false/' {lightdm_config}\", \"Disable autologin guest\", ask=False)\n",
    "        print_success(\"Autologin disabled\")\n",
    "    else:\n",
    "        print_warning(\"lightdm.conf not found - may be using different display manager\")\n",
    "\n",
    "def search_prohibited_files():\n",
    "    \"\"\"Search for prohibited files\"\"\"\n",
    "    print_header(\"PROHIBITED FILES SEARCH\")\n",
    "    \n",
    "    print(Colors.BOLD + \"Common prohibited file types:\" + Colors.END)\n",
    "    print(\"Media: mp3, mp4, mov, avi, mkv, flv, wav, m4a\")\n",
    "    print(\"Images: jpg, jpeg, png, gif (sometimes allowed)\")\n",
    "    print(\"Games: .exe (wine), game-related\")\n",
    "    \n",
    "    extensions = input(\"\\nEnter file extensions to search (e.g., mp3 mp4 avi): \").split()\n",
    "    \n",
    "    for ext in extensions:\n",
    "        print(f\"\\n{Colors.BOLD}Searching for *.{ext} files:{Colors.END}\")\n",
    "        cmd = f\"find /home -name '*.{ext}' -type f 2>/dev/null\"\n",
    "        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)\n",
    "        if result.stdout:\n",
    "            print(result.stdout)\n",
    "            if input(f\"Delete all *.{ext} files? (yes/no): \").lower() == 'yes':\n",
    "                run_command(f\"find /home -name '*.{ext}' -type f -delete\", f\"Delete *.{ext} files\", ask=False)\n",
    "        else:\n",
    "            print(f\"No *.{ext} files found\")\n",
    "    \n",
    "    # Search for hacking tools\n",
    "    print(f\"\\n{Colors.BOLD}Searching for hacking tools:{Colors.END}\")\n",
    "    tools = [\"netcat\", \"nc\", \"nmap\", \"john\", \"hydra\", \"ophcrack\", \"wireshark\", \"metasploit\", \"armitage\", \"aircrack-ng\", \"burpsuite\"]\n",
    "    found_tools = []\n",
    "    for tool in tools:\n",
    "        result = subprocess.run(f\"which {tool}\", shell=True, capture_output=True)\n",
    "        if result.returncode == 0:\n",
    "            location = result.stdout.decode().strip()\n",
    "            print_warning(f\"Found: {tool} at {location}\")\n",
    "            found_tools.append(tool)\n",
    "    \n",
    "    if found_tools and input(\"\\nRemove found hacking tools? (y/n): \").lower() == 'y':\n",
    "        for tool in found_tools:\n",
    "            run_command(f\"apt-get remove --purge {tool} -y\", f\"Remove {tool}\")\n",
    "\n",
    "def remove_prohibited_software():\n",
    "    \"\"\"Remove commonly prohibited software\"\"\"\n",
    "    print_header(\"REMOVE PROHIBITED SOFTWARE\")\n",
    "    \n",
    "    print(Colors.BOLD + \"Checking for prohibited services/software...\" + Colors.END)\n",
    "    \n",
    "    prohibited = [\"telnet\", \"ftp\", \"vsftpd\", \"rsh\", \"rlogin\", \"nfs\", \"nis\", \"samba\", \"apache2\", \"bind9\", \"nginx\", \"vnc\"]\n",
    "    \n",
    "    run_command(\"dpkg --list | egrep 'telnet|ftp|vsftpd|rsh|rlogin|nfs|nis|samba|apache|bind9|nginx|vnc'\", \n",
    "                \"List prohibited packages\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"Remove packages individually:\" + Colors.END)\n",
    "    for pkg in prohibited:\n",
    "        result = subprocess.run(f\"dpkg -l | grep -w {pkg}\", shell=True, capture_output=True)\n",
    "        if result.returncode == 0:\n",
    "            if input(f\"Remove {pkg}? (y/n): \").lower() == 'y':\n",
    "                run_command(f\"apt-get remove --purge {pkg} -y\", f\"Remove {pkg}\", ask=False)\n",
    "    \n",
    "    run_command(\"apt-get autoremove -y\", \"Clean up dependencies\", ask=False)\n",
    "\n",
    "def secure_ssh():\n",
    "    \"\"\"Secure SSH configuration\"\"\"\n",
    "    print_header(\"SSH SECURITY\")\n",
    "    \n",
    "    ssh_config = \"/etc/ssh/sshd_config\"\n",
    "    if not os.path.exists(ssh_config):\n",
    "        print_warning(\"SSH not installed or config not found\")\n",
    "        return\n",
    "    \n",
    "    backup = f\"{ssh_config}.bak.{datetime.now().strftime('%Y%m%d_%H%M%S')}\"\n",
    "    run_command(f\"cp {ssh_config} {backup}\", \"Backup SSH config\", ask=False)\n",
    "    \n",
    "    print(\"\\nRecommended SSH hardening:\")\n",
    "    print(\"  PermitRootLogin no\")\n",
    "    print(\"  PasswordAuthentication yes\")\n",
    "    print(\"  PermitEmptyPasswords no\")\n",
    "    print(\"  Protocol 2\")\n",
    "    print(\"  X11Forwarding no\")\n",
    "    \n",
    "    if input(\"\\nApply recommended SSH settings? (y/n): \").lower() == 'y':\n",
    "        run_command(\"sed -i 's/^#*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config\", \"Disable root login\", ask=False)\n",
    "        run_command(\"sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config\", \"Enable password auth\", ask=False)\n",
    "        run_command(\"sed -i 's/^#*PermitEmptyPasswords.*/PermitEmptyPasswords no/' /etc/ssh/sshd_config\", \"Disable empty passwords\", ask=False)\n",
    "        run_command(\"sed -i 's/^#*X11Forwarding.*/X11Forwarding no/' /etc/ssh/sshd_config\", \"Disable X11 forwarding\", ask=False)\n",
    "        run_command(\"systemctl restart sshd\", \"Restart SSH service\")\n",
    "\n",
    "def configure_sudoers():\n",
    "    \"\"\"Configure sudo to require authentication\"\"\"\n",
    "    print_header(\"SUDOERS CONFIGURATION\")\n",
    "    \n",
    "    print(Colors.BOLD + \"Ensuring sudo requires authentication...\" + Colors.END)\n",
    "    \n",
    "    # Check if authentication is required\n",
    "    result = subprocess.run(\"grep 'Defaults authenticate' /etc/sudoers\", shell=True, capture_output=True)\n",
    "    if result.returncode != 0:\n",
    "        print_warning(\"'Defaults authenticate' not found in /etc/sudoers\")\n",
    "        if input(\"Add authentication requirement? (y/n): \").lower() == 'y':\n",
    "            run_command(\"echo 'Defaults authenticate' >> /etc/sudoers\", \"Add authentication requirement\")\n",
    "    else:\n",
    "        print_success(\"Sudo authentication already configured\")\n",
    "\n",
    "def check_services():\n",
    "    \"\"\"List and manage services\"\"\"\n",
    "    print_header(\"SERVICE MANAGEMENT\")\n",
    "    \n",
    "    print(Colors.BOLD + \"Currently active services:\" + Colors.END)\n",
    "    run_command(\"systemctl list-units --type=service --state=active\", \"List active services\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.YELLOW + \"Review services and disable unnecessary ones\" + Colors.END)\n",
    "    print(\"Common suspicious services: nginx, apache2, telnet, ftp, vsftpd\")\n",
    "    \n",
    "    while True:\n",
    "        service = input(\"\\nEnter service to disable (or press Enter to skip): \")\n",
    "        if not service:\n",
    "            break\n",
    "        run_command(f\"systemctl stop {service}\", f\"Stop {service}\")\n",
    "        run_command(f\"systemctl disable {service}\", f\"Disable {service}\")\n",
    "\n",
    "def kernel_hardening():\n",
    "    \"\"\"Configure kernel security parameters\"\"\"\n",
    "    print_header(\"KERNEL HARDENING\")\n",
    "    \n",
    "    sysctl_conf = \"/etc/sysctl.conf\"\n",
    "    run_command(f\"cp {sysctl_conf} {sysctl_conf}.bak\", \"Backup sysctl.conf\", ask=False)\n",
    "    \n",
    "    print(Colors.BOLD + \"Security parameters to configure:\" + Colors.END)\n",
    "    print(\"  net.ipv4.ip_forward=0 (disable IP forwarding)\")\n",
    "    print(\"  net.ipv4.tcp_syncookies=1 (enable SYN cookie protection)\")\n",
    "    \n",
    "    if input(\"\\nApply kernel hardening? (y/n): \").lower() == 'y':\n",
    "        run_command(\"sed -i 's/^#*net.ipv4.ip_forward.*/net.ipv4.ip_forward=0/' /etc/sysctl.conf\", \"Disable IP forwarding\", ask=False)\n",
    "        run_command(\"sed -i 's/^#*net.ipv4.tcp_syncookies.*/net.ipv4.tcp_syncookies=1/' /etc/sysctl.conf\", \"Enable SYN cookies\", ask=False)\n",
    "        run_command(\"sysctl -p\", \"Apply sysctl changes\", ask=False)\n",
    "\n",
    "def check_file_permissions():\n",
    "    \"\"\"Check and fix critical file permissions\"\"\"\n",
    "    print_header(\"FILE PERMISSIONS\")\n",
    "    \n",
    "    print(Colors.BOLD + \"Checking critical file permissions...\" + Colors.END)\n",
    "    \n",
    "    # Check /etc/shadow\n",
    "    run_command(\"ls -l /etc/shadow\", \"Check /etc/shadow permissions\", ask=False)\n",
    "    if input(\"Set /etc/shadow to 640? (y/n): \").lower() == 'y':\n",
    "        run_command(\"chmod 640 /etc/shadow\", \"Set shadow permissions\")\n",
    "    \n",
    "    # Check /etc/passwd\n",
    "    run_command(\"ls -l /etc/passwd\", \"Check /etc/passwd permissions\", ask=False)\n",
    "    if input(\"Set /etc/passwd to 644? (y/n): \").lower() == 'y':\n",
    "        run_command(\"chmod 644 /etc/passwd\", \"Set passwd permissions\")\n",
    "\n",
    "def check_backdoors():\n",
    "    \"\"\"Check for backdoors and suspicious connections\"\"\"\n",
    "    print_header(\"BACKDOOR DETECTION\")\n",
    "    \n",
    "    print(Colors.BOLD + \"Checking for listening ports and connections...\" + Colors.END)\n",
    "    run_command(\"ss -tlnp\", \"Show listening TCP ports\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"Checking cron jobs for backdoors...\" + Colors.END)\n",
    "    run_command(\"cat /etc/crontab\", \"Show crontab\", ask=False)\n",
    "    \n",
    "    print_warning(\"Look for suspicious entries like netcat (nc), reverse shells, or unusual scripts\")\n",
    "    \n",
    "    if input(\"\\nKill all netcat processes? (y/n): \").lower() == 'y':\n",
    "        run_command(\"pkill -f nc.traditional\", \"Kill netcat traditional\", ask=False)\n",
    "        run_command(\"pkill -f nc\", \"Kill netcat\", ask=False)\n",
    "        run_command(\"which nc.traditional\", \"Find netcat location\", ask=False)\n",
    "        if input(\"Remove netcat binary? (y/n): \").lower() == 'y':\n",
    "            run_command(\"rm /usr/bin/nc.traditional\", \"Remove netcat\", ask=False)\n",
    "\n",
    "def configure_firefox():\n",
    "    \"\"\"Display Firefox security settings\"\"\"\n",
    "    print_header(\"FIREFOX SECURITY\")\n",
    "    \n",
    "    print(Colors.BOLD + \"Manual Firefox configuration (Privacy & Security):\" + Colors.END)\n",
    "    print(\"✓ Don't ask to save logins\")\n",
    "    print(\"✓ Show alerts about passwords for breached websites\")\n",
    "    print(\"✓ Firefox can remember history (OK)\")\n",
    "    print(\"✓ Block pop-up windows\")\n",
    "    print(\"✓ Warn you about add-ons\")\n",
    "    print(\"✓ Block dangerous and deceptive content\")\n",
    "    print(\"✓ Block dangerous downloads\")\n",
    "    print(\"✓ Consider deleting cookies\")\n",
    "    print(\"\\nPress Enter to continue...\")\n",
    "    input()\n",
    "\n",
    "def security_audit():\n",
    "    \"\"\"Run comprehensive security audit\"\"\"\n",
    "    print_header(\"SECURITY AUDIT\")\n",
    "    \n",
    "    print(Colors.BOLD + \"1. Users with UID 0 (should only be root):\" + Colors.END)\n",
    "    run_command(\"awk -F: '$3 == 0 {print $1}' /etc/passwd\", \"Check UID 0 users\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"2. Users with empty passwords:\" + Colors.END)\n",
    "    run_command(\"awk -F: '$2 == \\\"\\\" {print $1}' /etc/shadow 2>/dev/null\", \"Check empty passwords\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"3. Checking for world-writable files:\" + Colors.END)\n",
    "    print_warning(\"This may take several minutes...\")\n",
    "    run_command(\"find / -xdev -type f -perm -0002 -ls 2>/dev/null | head -20\", \"Find world-writable files\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"4. Checking SUID/SGID files:\" + Colors.END)\n",
    "    run_command(\"find / -perm -4000 -type f 2>/dev/null | head -20\", \"Find SUID files\", ask=False)\n",
    "    \n",
    "    print(\"\\n\" + Colors.BOLD + \"5. Checking all user groups:\" + Colors.END)\n",
    "    run_command(\"cat /etc/group\", \"List all groups\", ask=False)\n",
    "\n",
    "def main_menu():\n",
    "    \"\"\"Display and handle main menu\"\"\"\n",
    "    while True:\n",
    "        print_header(\"CYBERPATRIOT LINUX SECURITY SCRIPT\")\n",
    "        print(\"0.  System Information\")\n",
    "        print(\"1.  System Updates\")\n",
    "        print(\"2.  Configure Automatic Updates\")\n",
    "        print(\"3.  Install & Configure Antivirus (ClamAV)\")\n",
    "        print(\"4.  Configure Firewall (UFW)\")\n",
    "        print(\"5.  User Management\")\n",
    "        print(\"6.  Password Policies\")\n",
    "        print(\"7.  Disable Autologin\")\n",
    "        print(\"8.  Search for Prohibited Files\")\n",
    "        print(\"9.  Remove Prohibited Software\")\n",
    "        print(\"10. Secure SSH\")\n",
    "        print(\"11. Configure Sudoers\")\n",
    "        print(\"12. Check & Manage Services\")\n",
    "        print(\"13. Kernel Hardening (IPv4/SYN Cookies)\")\n",
    "        print(\"14. Check File Permissions\")\n",
    "        print(\"15. Check for Backdoors\")\n",
    "        print(\"16. Firefox Security Settings\")\n",
    "        print(\"17. Security Audit\")\n",
    "        print(\"18. Run Critical Tasks (Auto Mode)\")\n",
    "        print(\"99. Exit\")\n",
    "        \n",
    "        choice = input(\"\\nSelect option: \")\n",
    "        \n",
    "        if choice == '0':\n",
    "            system_info()\n",
    "        elif choice == '1':\n",
    "            system_updates()\n",
    "        elif choice == '2':\n",
    "            configure_automatic_updates()\n",
    "        elif choice == '3':\n",
    "            install_antivirus()\n",
    "        elif choice == '4':\n",
    "            configure_firewall()\n",
    "        elif choice == '5':\n",
    "            manage_users()\n",
    "        elif choice == '6':\n",
    "            password_policies()\n",
    "        elif choice == '7':\n",
    "            disable_autologin()\n",
    "        elif choice == '8':\n",
    "            search_prohibited_files()\n",
    "        elif choice == '9':\n",
    "            remove_prohibited_software()\n",
    "        elif choice == '10':\n",
    "            secure_ssh()\n",
    "        elif choice == '11':\n",
    "            configure_sudoers()\n",
    "        elif choice == '12':\n",
    "            check_services()\n",
    "        elif choice == '13':\n",
    "            kernel_hardening()\n",
    "        elif choice == '14':\n",
    "            check_file_permissions()\n",
    "        elif choice == '15':\n",
    "            check_backdoors()\n",
    "        elif choice == '16':\n",
    "            configure_firefox()\n",
    "        elif choice == '17':\n",
    "            security_audit()\n",
    "        elif choice == '18':\n",
    "            print_warning(\"Running critical tasks in sequence...\")\n",
    "            system_info()\n",
    "            system_updates()\n",
    "            configure_automatic_updates()\n",
    "            install_antivirus()\n",
    "            configure_firewall()\n",
    "            password_policies()\n",
    "            disable_autologin()\n",
    "            remove_prohibited_software()\n",
    "            secure_ssh()\n",
    "            configure_sudoers()\n",
    "            kernel_hardening()\n",
    "            check_file_permissions()\n",
    "            security_audit()\n",
    "            print_success(\"All automated tasks completed!\")\n",
    "        elif choice == '99':\n",
    "            print(\"\\n\" + Colors.GREEN + \"Good luck with the competition!\" + Colors.END)\n",
    "            break\n",
    "        else:\n",
    "            print_error(\"Invalid option!\")\n",
    "        \n",
    "        input(\"\\nPress Enter to continue...\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    try:\n",
    "        check_root()\n",
    "        main_menu()\n",
    "    except KeyboardInterrupt:\n",
    "        print(\"\\n\\nExiting...\")\n",
    "        sys.exit(0)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
